import { useState, useEffect, useCallback } from 'react'
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { ClockClockwise, Eye, CircleNotch, GitCompare, DownloadSimple } from '@phosphor-icons/react'
import { formatDistanceToNow } from 'date-fns'
import { toast } from 'sonner'
import { envService } from '@/lib/services/env-service'
import { NutritionLabel } from './NutritionLabel'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

export function NutritionLabelHistory({ formulationId }) {
  const [labels, setLabels] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [selectedLabel, setSelectedLabel] = useState(null)
  const [compareLabels, setCompareLabels] = useState([])
  const [showViewDialog, setShowViewDialog] = useState(false)
  const [showCompareDialog, setShowCompareDialog] = useState(false)

  const loadHistory = useCallback(async () => {
    if (!formulationId) return

    setLoading(true)
    setError(null)

    try {
      const backendUrl = envService.getBackendUrl()
      const authHeaders = envService.getAuthHeaders()

      const response = await fetch(
        `${backendUrl}/api/formulations/${formulationId}/nutrition-labels?limit=50`,
        {
          headers: {
            ...authHeaders,
            'Content-Type': 'application/json',
          },
        }
      )

      if (!response.ok) {
        const errorText = await response.text()
        let errorMessage
        try {
          const errorJson = JSON.parse(errorText)
          errorMessage = errorJson.detail || errorText
        } catch {
          errorMessage = errorText
        }
        throw new Error(`Failed to load nutrition label history: ${errorMessage}`)
      }

      const data = await response.json()
      setLabels(data.labels || [])
    } catch (err) {
      console.error('Failed to load nutrition label history:', err)
      setError(err.message)
      toast.error('Failed to load nutrition label history')
    } finally {
      setLoading(false)
    }
  }, [formulationId])

  useEffect(() => {
    loadHistory()
  }, [loadHistory])

  const handleViewLabel = (label) => {
    setSelectedLabel(label)
    setShowViewDialog(true)
  }

  const handleSelectForCompare = (label) => {
    if (compareLabels.some((l) => l.labelId === label.labelId)) {
      // Remove if already selected
      setCompareLabels(compareLabels.filter((l) => l.labelId !== label.labelId))
    } else if (compareLabels.length < 2) {
      // Add if less than 2 selected
      setCompareLabels([...compareLabels, label])
    } else {
      toast.error('You can only compare 2 labels at a time')
    }
  }

  const handleCompare = () => {
    if (compareLabels.length !== 2) {
      toast.error('Please select exactly 2 labels to compare')
      return
    }
    setShowCompareDialog(true)
  }

  const handleExportCSV = () => {
    if (labels.length === 0) {
      toast.error('No labels to export')
      return
    }

    // Create CSV content
    const headers = ['Version', 'Calories', 'Serving Size', 'Generated At', 'Generated By']
    const rows = labels.map((label) => [
      label.version,
      label.calories,
      `${label.servingSize}${label.servingSizeUnit}`,
      label.generatedAt,
      label.generatedBy || 'system',
    ])

    const csvContent = [
      headers.join(','),
      ...rows.map((row) => row.join(',')),
    ].join('\n')

    // Download
    const blob = new Blob([csvContent], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `nutrition-label-history-${formulationId}.csv`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    toast.success('CSV exported successfully')
  }

  // Convert label to NutritionLabel component format
  const convertLabelToNutritionFacts = (label) => ({
    formulation_id: label.formulationId,
    formulation_name: label.formulationName || 'Formulation',
    serving_size: label.servingSize,
    serving_size_unit: label.servingSizeUnit,
    servings_per_container: label.servingsPerContainer,
    calories: label.calories,
    nutrients: label.nutrients || {},
    additional_nutrients: label.additionalNutrients || [],
  })

  const getDifferenceIndicator = (current, previous, field) => {
    if (!previous) return null
    
    const currentValue = field === 'calories' ? current.calories : current.servingSize
    const previousValue = field === 'calories' ? previous.calories : previous.servingSize
    
    if (currentValue > previousValue) {
      return <span className="text-red-500 text-xs ml-1">↑</span>
    } else if (currentValue < previousValue) {
      return <span className="text-green-500 text-xs ml-1">↓</span>
    }
    return null
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="flex flex-col items-center gap-3">
            <CircleNotch size={32} className="animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Loading nutrition label history...</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (error) {
    return (
      <Card>
        <CardContent className="py-6">
          <div className="flex flex-col items-center gap-3 text-destructive">
            <p className="text-sm font-medium">Failed to load history</p>
            <p className="text-xs text-muted-foreground">{error}</p>
            <Button variant="outline" size="sm" onClick={loadHistory}>
              Retry
            </Button>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (labels.length === 0) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="flex flex-col items-center gap-3 text-muted-foreground">
            <ClockClockwise size={32} className="opacity-50" />
            <p className="text-sm">No nutrition labels found</p>
            <p className="text-xs">Generate a nutrition label to see it here</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Nutrition Label History</CardTitle>
              <CardDescription>
                {labels.length} version{labels.length !== 1 ? 's' : ''} saved
              </CardDescription>
            </div>
            <div className="flex gap-2">
              {compareLabels.length === 2 && (
                <Button variant="outline" size="sm" onClick={handleCompare} className="gap-2">
                  <GitCompare size={16} />
                  Compare Selected
                </Button>
              )}
              <Button variant="outline" size="sm" onClick={handleExportCSV} className="gap-2">
                <DownloadSimple size={16} />
                Export CSV
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[80px]">Version</TableHead>
                <TableHead>Calories</TableHead>
                <TableHead>Serving Size</TableHead>
                <TableHead>Generated</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {labels.map((label, index) => {
                const previousLabel = labels[index + 1]
                const isSelectedForCompare = compareLabels.some((l) => l.labelId === label.labelId)
                
                return (
                  <TableRow 
                    key={label.labelId}
                    className={isSelectedForCompare ? 'bg-primary/5' : ''}
                  >
                    <TableCell>
                      <Badge variant={label.version === labels[0].version ? 'default' : 'secondary'}>
                        v{label.version}
                        {label.version === labels[0].version && (
                          <span className="ml-1 text-[10px]">latest</span>
                        )}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <span className="font-medium">{label.calories}</span> cal
                      {getDifferenceIndicator(label, previousLabel, 'calories')}
                    </TableCell>
                    <TableCell>
                      {label.servingSize}
                      {label.servingSizeUnit}
                      {getDifferenceIndicator(label, previousLabel, 'servingSize')}
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-col">
                        <span className="text-sm">
                          {formatDistanceToNow(new Date(label.generatedAt), { addSuffix: true })}
                        </span>
                        <span className="text-xs text-muted-foreground">
                          {new Date(label.generatedAt).toLocaleDateString()} {new Date(label.generatedAt).toLocaleTimeString()}
                        </span>
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleViewLabel(label)}
                          className="gap-2"
                        >
                          <Eye size={16} />
                          View
                        </Button>
                        <Button
                          variant={isSelectedForCompare ? 'default' : 'outline'}
                          size="sm"
                          onClick={() => handleSelectForCompare(label)}
                          className="gap-2"
                        >
                          <GitCompare size={16} />
                          {isSelectedForCompare ? 'Selected' : 'Compare'}
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* View Dialog */}
      <Dialog open={showViewDialog} onOpenChange={setShowViewDialog}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>
              Nutrition Label - Version {selectedLabel?.version}
            </DialogTitle>
            <DialogDescription>
              Generated {selectedLabel && formatDistanceToNow(new Date(selectedLabel.generatedAt), { addSuffix: true })}
            </DialogDescription>
          </DialogHeader>
          {selectedLabel && (
            <NutritionLabel nutritionFacts={convertLabelToNutritionFacts(selectedLabel)} />
          )}
        </DialogContent>
      </Dialog>

      {/* Compare Dialog */}
      <Dialog open={showCompareDialog} onOpenChange={setShowCompareDialog}>
        <DialogContent className="max-w-6xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Compare Nutrition Labels</DialogTitle>
            <DialogDescription>
              Version {compareLabels[0]?.version} vs Version {compareLabels[1]?.version}
            </DialogDescription>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-6">
            {compareLabels.map((label, index) => (
              <div key={label.labelId} className="space-y-2">
                <div className="flex items-center justify-between">
                  <Badge variant={index === 0 ? 'default' : 'secondary'}>
                    Version {label.version}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    {formatDistanceToNow(new Date(label.generatedAt), { addSuffix: true })}
                  </span>
                </div>
                <NutritionLabel nutritionFacts={convertLabelToNutritionFacts(label)} />
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
